### ISSUE TITLE
Column Drag and Drop issue with excluded columns

### ISSUE THREAD

**Issue by mcmastermind** [gregnb/mui-datatables#1364]
I am experiencing an issue when dragging columns when there are columns with the display property set to exclude. It looks like, in useColumnDrop.js the headCellRefs array indexes do not align with the columnOrder argument.

## Expected Behavior

Columns should be able to drag and drop smoothly regardless of display property.

## Current Behavior

useColumnDrop.js throws and error on line 38 when columns with the property `display: 'exclude'` is set.

Error: `TypeError: Cannot read property 'offsetWidth' of undefined`

## Steps to Reproduce

[Sandbox Example](https://codesandbox.io/s/muidatatables-resize-columns-example-oyzwx)

1. Define your columns
2. Set one column with `display: 'exclude'`
3. Render datatable
4. Try to drag a column

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.10.2     |
| MUI-datatables  |    3.1.1     |
| React        |    16.13.1     |
| browser      |    FireFox     |

**Comment by patorjk** [comment]
Thank you for the report. I have a fix working in dev. I'm going to test it a little more and see if I can resolve an issue another person is having but hopefully a patch will be out soon.

**Comment by patorjk** [comment]
If you have a moment, can you try out this beta version I just published:

npm install mui-datatables@3.1.2-beta.0

I believe it should resolve this issue.

**Comment by mcmastermind** [comment]
I am still experiencing the same behavior. I also updated the [code sandbox](https://codesandbox.io/s/muidatatables-resize-columns-example-oyzwx) to use the beta version as well

**Comment by patorjk** [comment]
Should be fixed in mui-datatables@3.1.2-beta.1, let me know if this works for you:

https://codesandbox.io/s/muidatatables-drag-columns-error-nzf03

It looks like the issue that time was the "exclude" is an invalid value for display (display takes in "true", "false" or "excluded"). However, this problem was hidden because the table only displayed columns if display equaled "true", making it seem like "exclude" worked. However, if you were to click the ViewColumn button in the toolbar, the column would be there and you could show it (since that dropdown menu was based on the input "excluded").

In mui-datatables@3.1.2-beta.1 I've updated the code to account for this. "true" and "false" work as expected, and anything other than those two values basically acts as the "excluded" input.

**Comment by mcmastermind** [comment]
Works like a charm! Keep up the good work, and thank you for tackling this so quickly.

**Comment by patorjk** [comment]
No problem, thanks for the report!
