### ISSUE TITLE
Warning: Failed prop type: Material-UI: you are using a deprecated typography variant: `subheading` that will be removed in the next major release.

### ISSUE THREAD

**Issue by jkeruzec** [gregnb/mui-datatables#354]
Please upgrade material-ui typography variant to latest version.

Thanks :)

**Comment by gregnb** [comment]
It'll be done tonight

**Comment by mking42** [comment]
https://github.com/gregnb/mui-datatables/issues/333

**Comment by aishmitk** [comment]
I seem to be getting same error, running the latest version of material-ui/core and latest version of mui-datatables

When i expand the error it points towards `getMuiTheme()`
![image](https://user-images.githubusercontent.com/24919332/51184511-764c6f00-18a2-11e9-8db4-edd246ddad07.png)

**Comment by jkeruzec** [comment]
FYI, Material UI is preparing a version V4 with removal of deprecated behaviour.

https://github.com/mui-org/material-ui/issues/13663

**Comment by gregnb** [comment]
This issue has been resolved in beta-53. Please let me know if there are any further problems

**Comment by foxmicha** [comment]
Still receiving this issue in 2.0.0-beta-53:

![image](https://user-images.githubusercontent.com/29128205/51759824-17070f80-2097-11e9-84cf-9a23d38dc85a.png)

Code in question:

```js
getMuiTheme = () => createMuiTheme({
        overrides: {
            //@ts-ignore
            MUIDataTableBodyCell: {
                root: {
                    padding: "4px"
                }
            },
            MUIDataTableHeadCell: {
                root: {
                    padding: "4px"
                }
            }
        }
    })

    render() {
        return (
            <>
            <MuiThemeProvider theme={this.getMuiTheme()}>
                <MUIDataTable
                    title={"DataTable Demo"}
                    data={randomData}
                    columns={muiDataTableColumns}
                    options={options}
                />
            </MuiThemeProvider>
            </>
        );
    }
```

**Comment by gregnb** [comment]
@foxmicha Can you provide your environment information? mui ver, etc

**Comment by foxmicha** [comment]
material-ui/core: 3.7.1
material-ui/icons: 3.0.2
mui-datatables: 2.0.0-beta-53
