### ISSUE TITLE
changedColumn gets the value instead of column name on onFilterChange event

### ISSUE THREAD

**Issue by blopez2010** [gregnb/mui-datatables#483]
When the filter is changed and according to the parameter name, `changedColumn` should be the name of the column to be filtered, instead, I'm getting the value of the column to be filtered.

## Expected Behavior
`changedColumn` should get the column name to be filtered instead.

## Current Behavior
`changedColumn` is getting the value to be filtered.

## Steps to Reproduce (for bugs)
I didn't do too much to repro it, just add the event `onFilterChange` and a `console.log(changedColumn, filterList)` and that's it.

```
      onFilterChange: (changedColumn, filterList) => {
        console.log(changedColumn, filterList)
      }
```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  ^3.9.2       |
| MUI-datatables  |  ^2.0.0-beta.56       |
| React        |   ^16.8.1      |
| browser      |   Chrome Version 72.0.3626.121      |

**Comment by gregnb** [comment]
@blopez2010 Thanks for finding the issue. Can you send in a PR?

**Comment by gabrielliwerant** [comment]
PR up for this issue.

**Comment by gregnb** [comment]
Should be resolved upgrade to the latest version 2.0.0

**Comment by cherukumilli** [comment]
@gregnb @gabrielliwerant @blopez2010 
I still see the issue in the latest version 2.0.0.

**Comment by gabrielliwerant** [comment]
Yes, that makes sense, the PR has not been merged yet.

**Comment by cherukumilli** [comment]
@gabrielliwerant - thx for reopening the issue. Is there a temporary workaround that you can suggest till the PR gets merged?

**Comment by gabrielliwerant** [comment]
@cherukumilli Unfortunately, it's not a one-liner. The main fix is here https://github.com/gregnb/mui-datatables/pull/560/commits/8760dfc0793f4b21e96c766a0df4e6a5ac4bad50. If you had to move forward before this gets merged, you could fork and apply that fix, at your own risk, of course!

**Comment by gabrielliwerant** [comment]
Closing this issue as it should have been resolved by the PR referenced here, and is a part of the release made shortly afterwards.
