### ISSUE TITLE
Column header row not resizing as expected

### ISSUE THREAD

**Issue by m-preiner** [gregnb/mui-datatables#754]
## Expected Behavior
When there are long column names, the header row height is expected to adjust to fit the entire wrapped column name. 

## Current Behavior
The column header cells are not resizing their height when the text begins to wrap.  This causes the column headers to overlap with the first row. 

## Steps to Reproduce (for bugs)
I've posted a codesandbox example at :
https://codesandbox.io/embed/frosty-beaver-kcwnt. 
Note: you'll probably need to open in the editor and then horizontally stretch the browser pane to put the table out of "card" mode and into "table" mode.

To reproduce
1. Make a table with a large number of columns and fairly long columns names.
2. Note that the column names overlap the first row...see screenshot below.

<img width="1015" alt="ColumnName overlap" src="https://user-images.githubusercontent.com/41084152/60838040-16d47980-a1ca-11e9-898d-61e5b422a2c6.png">

**Comment by m-preiner** [comment]
Update: It looks this issue does not occur with previous releases. For example, mui-datatables@2.0.0 does not have this problem.

**Comment by gabrielliwerant** [comment]
Thank you for pointing this out. I know what the issue is and will have a fix shortly.

**Comment by gabrielliwerant** [comment]
Should be resolved in `2.6.2`.

**Comment by m-preiner** [comment]
Awesome, thanks!

**Comment by hibc** [comment]
@gabrielliwerant 
Hello I just updated to v2.6.2, but I'm still having the resizing issue.
I have about 20 columns.

**Comment by gabrielliwerant** [comment]
@hibc Hello. That sounds like a different issue. The one mentioned here initially has been resolved as far as I can tell.

If you like, you can open up a new ticket for it with steps to reproduce, and we can discuss it there. My feeling though is that you're running into limitations due to lack of remaining screen width. I don't know if that situation has been addressed as far as resizable columns yet. We'd need to determine which rows get width stolen to compensate, and there are other issues with resizable columns such as lack of minimum width which as also probably contributing.
